// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCYELlCo5qHZRDSEbWRekyRVpWZTfVt38',
    appId: '1:820521949909:web:a4612bd2a001e012c2e05c',
    messagingSenderId: '820521949909',
    projectId: 'portcare-utkarsh',
    authDomain: 'portcare-utkarsh.firebaseapp.com',
    storageBucket: 'portcare-utkarsh.firebasestorage.app',
    measurementId: 'G-96K24H4SW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsFMCGi9zYd4EqsDoXVEgKYbQQIYZ-wb8',
    appId: '1:820521949909:android:9b994148d5b4e945c2e05c',
    messagingSenderId: '820521949909',
    projectId: 'portcare-utkarsh',
    storageBucket: 'portcare-utkarsh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmBA238_TVmoqYQXk9AGsZ3wgCLufPM_Y',
    appId: '1:820521949909:ios:402e5ae9d8397581c2e05c',
    messagingSenderId: '820521949909',
    projectId: 'portcare-utkarsh',
    storageBucket: 'portcare-utkarsh.firebasestorage.app',
    iosBundleId: 'com.example.portcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmBA238_TVmoqYQXk9AGsZ3wgCLufPM_Y',
    appId: '1:820521949909:ios:402e5ae9d8397581c2e05c',
    messagingSenderId: '820521949909',
    projectId: 'portcare-utkarsh',
    storageBucket: 'portcare-utkarsh.firebasestorage.app',
    iosBundleId: 'com.example.portcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCYELlCo5qHZRDSEbWRekyRVpWZTfVt38',
    appId: '1:820521949909:web:b8273ead080c1eccc2e05c',
    messagingSenderId: '820521949909',
    projectId: 'portcare-utkarsh',
    authDomain: 'portcare-utkarsh.firebaseapp.com',
    storageBucket: 'portcare-utkarsh.firebasestorage.app',
    measurementId: 'G-3S8DBMVZP2',
  );
}
